// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "url": "https://github.com/adohong4"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agency/create": {
            "post": {
                "description": "Create GovAgency handler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Goverment Agency"
                ],
                "summary": "Create  Agency",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.GovAgency"
                        }
                    }
                }
            }
        },
        "/agency/getAll": {
            "get": {
                "description": "Get all Goverment Agency with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Goverment Agency"
                ],
                "summary": "Get all Goverment Agency",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "page",
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "size",
                        "description": "number of elements per page",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "orderBy",
                        "description": "filter name",
                        "name": "orderBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GovAgency"
                        }
                    }
                }
            }
        },
        "/agency/search": {
            "get": {
                "description": "Search Goverment Agency by Name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Goverment Agency"
                ],
                "summary": "Search by Name",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "page",
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "size",
                        "description": "number of elements per page",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "orderBy",
                        "description": "filter name",
                        "name": "orderBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GovAgency"
                        }
                    }
                }
            }
        },
        "/agency/{id}": {
            "get": {
                "description": "Get by Goverment Agency handler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NGoverment Agency"
                ],
                "summary": "Get by Goverment Agency ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GovAgency"
                        }
                    }
                }
            },
            "put": {
                "description": "Update GovAgency handler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Goverment Agency"
                ],
                "summary": "Update Goverment Agency",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GovAgency"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete by id GovAgency handler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Goverment Agency"
                ],
                "summary": "Delete Goverment Agency",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GovAgency"
                        }
                    }
                }
            }
        },
        "/auth/all": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a paginated list of all users (admin only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "List all users (paginated)",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field",
                        "name": "orderBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UsersList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/auth/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new user account. Typically used by administrators.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Create a new user (admin only)",
                "parameters": [
                    {
                        "description": "User information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserWithToken"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/auth/find": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Find users matching the given identity number with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Search users by identity number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identity number (full or partial)",
                        "name": "identity_no",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field",
                        "name": "orderBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UsersList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate user with identity number and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserWithToken"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invalidate the current session and remove session cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout user",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the profile of the currently logged-in user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get current authenticated user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/auth/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a user profile by user ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing user by ID (admin or own account)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Update user information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated user data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permanently delete a user account (admin or self-deletion)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Delete user account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Optimistic lock version (optional)",
                        "name": "version",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User deleted successfully",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "409": {
                        "description": "Conflict (version mismatch)",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/driver-license/{id}/add-wallet": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Add or update wallet address for a driving license",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrivingLicense"
                ],
                "summary": "Add wallet address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Driving License ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Wallet address details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.AddWalletRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DrivingLicense"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/driver-license/{id}/confirm-blockchain": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update blockchain transaction hash and set on_blockchain to true",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrivingLicense"
                ],
                "summary": "Confirm blockchain storage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Driving License ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Blockchain confirmation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.ConfirmBlockchainRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DrivingLicense"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/licenses/create": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Create a new driving license entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrivingLicense"
                ],
                "summary": "Create a new driving license",
                "parameters": [
                    {
                        "description": "Driving License object",
                        "name": "driving_license",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DrivingLicense"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.DrivingLicense"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/licenses/getAll": {
            "get": {
                "description": "Get a paginated list of all active driving licenses",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrivingLicense"
                ],
                "summary": "Get all driving licenses",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DrivingLicenseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/licenses/search": {
            "get": {
                "description": "Search for driving licenses by license number with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrivingLicense"
                ],
                "summary": "Search driving licenses by license number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "License number to search",
                        "name": "license_no",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DrivingLicenseList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/licenses/stats/city-detail": {
            "get": {
                "description": "Get count of driving licenses grouped by owner_city (province/city), with breakdown by status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrivingLicense"
                ],
                "summary": "Get detailed distribution by owner city and status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CityDetailDistributionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/licenses/stats/license-type": {
            "get": {
                "description": "Get count of driving licenses by license type (A1, B1, B2, C, ...)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrivingLicense"
                ],
                "summary": "Get license type distribution",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LicenseTypeDistributionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/licenses/stats/license-type-detail": {
            "get": {
                "description": "Get count of driving licenses grouped by license_type, with breakdown by status (active, expired, pause, pending, revoke)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrivingLicense"
                ],
                "summary": "Get detailed distribution by license type and status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LicenseTypeDetailDistributionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/licenses/stats/status": {
            "get": {
                "description": "Get count of driving licenses by status (active, pending, expired, pause, revoke)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrivingLicense"
                ],
                "summary": "Get status distribution",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StatusDistributionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/licenses/{address}": {
            "get": {
                "description": "Get a single driving license by its Wallet Address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrivingLicense"
                ],
                "summary": "Get driving license by Wallet Address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Driving License Wallet Address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DrivingLicense"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/licenses/{id}": {
            "get": {
                "description": "Get a single driving license by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrivingLicense"
                ],
                "summary": "Get driving license by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Driving License ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DrivingLicense"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update an existing driving license by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrivingLicense"
                ],
                "summary": "Update a driving license",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Driving License ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Driving License object",
                        "name": "driving_license",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DrivingLicense"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DrivingLicense"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Soft delete a driving license by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DrivingLicense"
                ],
                "summary": "Delete a driving license",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Driving License ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Driving License object (for modifier)",
                        "name": "driving_license",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DrivingLicense"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DrivingLicense"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/news": {
            "get": {
                "description": "Get list of news with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News"
                ],
                "summary": "Get all news (paginated)",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.NewsList"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Create a new news article",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News"
                ],
                "summary": "Create news",
                "parameters": [
                    {
                        "description": "News object",
                        "name": "news",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.News"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.News"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/news/{id}": {
            "get": {
                "description": "Get single news (view count will increase)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News"
                ],
                "summary": "Get news by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "News ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.News"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Update an existing news",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News"
                ],
                "summary": "Update news by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "News ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "News object",
                        "name": "news",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.News"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.News"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Soft delete news",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "News"
                ],
                "summary": "Delete news by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "News ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.News"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/vehicle/create": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Creates a new vehicle registration record. The vehicle plate number must be unique.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-registration"
                ],
                "summary": "Create a new vehicle registration",
                "parameters": [
                    {
                        "description": "Vehicle registration data",
                        "name": "vehicle",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VehicleRegistration"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.VehicleRegistration"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/vehicle/getAll": {
            "get": {
                "description": "Returns a paginated list of active vehicle registrations.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-registration"
                ],
                "summary": "List all vehicle registrations",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default: 10)",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.VehicleRegistrationList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/vehicle/search": {
            "get": {
                "description": "Searches for active vehicle registrations containing the given plate number (partial match, case-insensitive).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-registration"
                ],
                "summary": "Search vehicle registrations by plate number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plate number (partial)",
                        "name": "vehicle_no",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default: 10)",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.VehicleRegistrationList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/vehicle/stats/brand": {
            "get": {
                "description": "Returns the top 5 most common vehicle brands and groups the rest under \"khác\".",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-registration"
                ],
                "summary": "Top vehicle brands distribution",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CountItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/vehicle/stats/status": {
            "get": {
                "description": "Returns count of motor vehicles (excluding motorcycles, mopeds, bicycles, electric bikes) by inspection status:\n- Valid: ExpiryDate \u003e= today\n- Expired: ExpiryDate \u003c today\n- Pending: No registration date or expiry date yet (e.g., new vehicles)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-registration"
                ],
                "summary": "Registration inspection status statistics (motor vehicles only)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CountItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/vehicle/stats/type": {
            "get": {
                "description": "Returns count of vehicles by type: xe đầu kéo, ô tô tải, ô tô con, xe khách, xe máy, and \"khác\" (others).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-registration"
                ],
                "summary": "Vehicle statistics by type",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CountItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/vehicle/{id}": {
            "get": {
                "description": "Retrieves a single active vehicle registration record by its UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-registration"
                ],
                "summary": "Get vehicle registration by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle Registration ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.VehicleRegistration"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Updates vehicle registration details by ID. Only provided fields are updated.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-registration"
                ],
                "summary": "Update an existing vehicle registration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle Registration ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated vehicle registration data",
                        "name": "vehicle",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VehicleRegistration"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.VehicleRegistration"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Marks a vehicle registration as inactive (soft delete).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-registration"
                ],
                "summary": "Soft delete a vehicle registration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle Registration ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.VehicleRegistration"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        },
        "/vehicle/{id}/confirm-blockchain": {
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Updates the blockchain transaction hash and sets on_blockchain to true after successful storage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle-registration"
                ],
                "summary": "Confirm blockchain storage for a vehicle registration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vehicle Registration ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Blockchain confirmation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ConfirmBlockchainRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.VehicleRegistration"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpErrors.RestError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.AddWalletRequest": {
            "type": "object",
            "required": [
                "wallet_address"
            ],
            "properties": {
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "http.ConfirmBlockchainRequest": {
            "type": "object",
            "required": [
                "blockchain_txhash"
            ],
            "properties": {
                "blockchain_txhash": {
                    "type": "string"
                },
                "on_blockchain": {
                    "type": "boolean"
                }
            }
        },
        "httpErrors.RestError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "models.CityDetailDistribution": {
            "type": "object",
            "properties": {
                "by_status": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CityStatusItem"
                    }
                },
                "owner_city": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.CityDetailDistributionResponse": {
            "type": "object",
            "properties": {
                "distribution": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CityDetailDistribution"
                    }
                },
                "grand_total": {
                    "type": "integer"
                }
            }
        },
        "models.CityStatusItem": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.ConfirmBlockchainRequest": {
            "type": "object",
            "required": [
                "blockchain_txhash"
            ],
            "properties": {
                "blockchain_txhash": {
                    "type": "string"
                },
                "on_blockchain": {
                    "type": "boolean"
                }
            }
        },
        "models.CountItem": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                }
            }
        },
        "models.DrivingLicense": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "authority_id": {
                    "description": "Mã nơi cấp",
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "blockchain_txhash": {
                    "description": "Mã lưu ở blockchain",
                    "type": "string"
                },
                "created_at": {
                    "description": "Thời gian tạo",
                    "type": "string"
                },
                "creator_id": {
                    "description": "ID của người tạo",
                    "type": "string"
                },
                "dob": {
                    "description": "Ngày sinh",
                    "type": "string"
                },
                "expiry_date": {
                    "description": "Ngày hết hạn (có thời hạn, vô thời hạn)",
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "identity_no": {
                    "description": "Căn cước công dân",
                    "type": "string"
                },
                "issue_date": {
                    "description": "Ngày cấp",
                    "type": "string"
                },
                "issuing_authority": {
                    "description": "Nơi cấp",
                    "type": "string"
                },
                "license_no": {
                    "description": "Số bằng lái",
                    "type": "string"
                },
                "license_type": {
                    "description": "Loại bằng lái (A1, B1, B2, ...)",
                    "type": "string"
                },
                "modifier_id": {
                    "description": "ID của người sửa",
                    "type": "string"
                },
                "nationality": {
                    "description": "Quốc tịch (Việt Nam, Hàn Quốc, ....)",
                    "type": "string"
                },
                "on_blockchain": {
                    "description": "Trạng thái lưu ở blockchain (lưa/ chưa lưu)",
                    "type": "boolean"
                },
                "owner_address": {
                    "description": "Địa chỉ",
                    "type": "string"
                },
                "owner_city": {
                    "type": "string"
                },
                "point": {
                    "description": "Điểm bằng lái xe (0 \u003c point \u003c 12)",
                    "type": "integer"
                },
                "status": {
                    "description": "Trạng thái (pending: chờ đợi, expired: hết hạn, active: hoạt động, pause: tạm dừng (point = 0), revoke: thu hồi)",
                    "type": "string"
                },
                "updated_at": {
                    "description": "Thời gian cập nhật",
                    "type": "string"
                },
                "version": {
                    "description": "Phiên bản, tự động tăng",
                    "type": "integer"
                },
                "wallet_address": {
                    "type": "string"
                }
            }
        },
        "models.DrivingLicenseList": {
            "type": "object",
            "properties": {
                "driver_licenses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DrivingLicense"
                    }
                },
                "has_more": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "models.GovAgency": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "description": "Đào tạo/đăng kiểm/cấp giấy tờ/...",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "models.LicenseTypeDetailDistribution": {
            "type": "object",
            "properties": {
                "by_status": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.StatusDistributionItem"
                    }
                },
                "license_type": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.LicenseTypeDetailDistributionResponse": {
            "type": "object",
            "properties": {
                "distribution": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.LicenseTypeDetailDistribution"
                    }
                },
                "grand_total": {
                    "type": "integer"
                }
            }
        },
        "models.LicenseTypeDistributionItem": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "license_type": {
                    "type": "string"
                }
            }
        },
        "models.LicenseTypeDistributionResponse": {
            "type": "object",
            "properties": {
                "distribution": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.LicenseTypeDistributionItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.News": {
            "type": "object"
        },
        "models.NewsList": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "news": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.News"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "models.StatusDistributionItem": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.StatusDistributionResponse": {
            "type": "object",
            "properties": {
                "distribution": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.StatusDistributionItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.User": {
            "type": "object",
            "required": [
                "hash_password",
                "id",
                "identity_no"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "created_at": {
                    "description": "Thời gian tạo",
                    "type": "string"
                },
                "creator_id": {
                    "description": "ID của người tạo",
                    "type": "string"
                },
                "hash_password": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "identity_no": {
                    "description": "CCCD",
                    "type": "string",
                    "maxLength": 20
                },
                "modifier_id": {
                    "description": "ID của người sửa",
                    "type": "string"
                },
                "password": {
                    "description": "Mật khẩu truyền thống",
                    "type": "string",
                    "minLength": 6
                },
                "role": {
                    "description": "Vai trò (admin, user, etc.)",
                    "type": "string",
                    "maxLength": 20
                },
                "updated_at": {
                    "description": "Thời gian cập nhật",
                    "type": "string"
                },
                "version": {
                    "description": "Phiên bản, tự động tăng",
                    "type": "integer"
                }
            }
        },
        "models.UserWithToken": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "models.UsersList": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.User"
                    }
                }
            }
        },
        "models.VehicleRegistration": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "blockchain_txhash": {
                    "description": "Mã lưu ở blockchain",
                    "type": "string"
                },
                "brand": {
                    "description": "Nhãn hiệu",
                    "type": "string"
                },
                "chassis_no": {
                    "description": "Số khung",
                    "type": "string"
                },
                "color_plate": {
                    "description": "Màu biển số xe",
                    "type": "string"
                },
                "color_vehicle": {
                    "description": "Màu xe",
                    "type": "string"
                },
                "created_at": {
                    "description": "Thời gian tạo",
                    "type": "string"
                },
                "creator_id": {
                    "description": "ID của người tạo",
                    "type": "string"
                },
                "engine_no": {
                    "description": "Số máy",
                    "type": "string"
                },
                "expiry_date": {
                    "description": "Ngày hết hạn dang kiem",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "issue_date": {
                    "description": "Ngày cấp",
                    "type": "string"
                },
                "issuer": {
                    "description": "Nơi cấp",
                    "type": "string"
                },
                "modifier_id": {
                    "description": "ID của người sửa",
                    "type": "string"
                },
                "on_blockchain": {
                    "description": "Trạng thái lưu ở blockchain (lưa/ chưa lưu)",
                    "type": "boolean"
                },
                "owner_id": {
                    "description": "ID chủ sở hữu",
                    "type": "string"
                },
                "owner_name": {
                    "description": "Chủ xe",
                    "type": "string"
                },
                "registration_date": {
                    "description": "Ngay dang kiem",
                    "type": "string"
                },
                "registration_place": {
                    "description": "nơi đăng kiểm",
                    "type": "string"
                },
                "seats": {
                    "description": "Số chỗ ngồi",
                    "type": "integer"
                },
                "status": {
                    "description": "Tình trạng (còn hiệu lực, hết hạn, bị thu hồi...)",
                    "type": "string"
                },
                "type_vehicle": {
                    "description": "Loại phương tiện",
                    "type": "string"
                },
                "updated_at": {
                    "description": "Thời gian cập nhật",
                    "type": "string"
                },
                "vehicle_no": {
                    "description": "Biển số xe",
                    "type": "string"
                },
                "version": {
                    "description": "Phiên bản, tự động tăng",
                    "type": "integer"
                }
            }
        },
        "models.VehicleRegistrationList": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                },
                "vehicle_registration": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.VehicleRegistration"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "description": "Type 'Bearer {your-jwt-token}' to authenticate. This is required for protected endpoints.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1/api",
	Schemes:          []string{},
	Title:            "Traffic License REST API",
	Description:      "REST API for Traffic License Management",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
